export default {
	'en-US': {
		login:'login',
		logon:'create account',
		
		account_p:'please input your account',
		pwd_p:'please input password',
		pwd_p_a:'input password again for confirmation',
		picture_p:'Please enter the graphic verification code',
		confirm:'confirm',
		basic:'Basic environment parameters',
		temp:'temperature',
		ph:'PH',
		oxygen:'dissolved-oxygen',
		history_chart:'Line chart of the historical data',
		alarm_temp:'Temperature alarm',
		alarm_temp_h:'High temperature alarm setting',
		alarm_temp_l:'Low temperature alarm setting',
		alarm_ph:'PH value alarm',
		alarm_ph_h:'PH value high alarm setting',
		alarm_ph_l:'PH value low alarm setting',
		alarm_oxygen:'Dissolved oxygen value alarm',
		alarm_oxygen_h:'High-level alarm setting of dissolved oxygen',
		alarm_oxygen_l:'Low-level alarm setting of dissolved oxygen',
		max_alarm:'High warning value',
		min_alarm:'Low warning value',
		copyright:'Copyright Ownership',
		school:'Ningbo Institute of Technology,\nZhejiang University',
		organization:'\nIntelligent Detection Institute',
		attribute:'device',
		device:'device symbol',
		pastday:'time  ',
		day:' days ago',
		last_month:'',
		last_week:'',
		average_week:'average-week',
		average_month:'average-month',
		strange_dot:'outlier',
		last_24h:'',
		last1:'the max of',
		last2:'the min of',
		average:' in the period of time',
		max:' in the period of time',
		inthelast24:'in the last 24 hours ',
		inthelastweek:'in the last week',
		inthelastmonth:'in the last month',
		min:' in the period of time',
		history:'',
		his1:'the max of ',
		his2:'the min of ',
		his3:'the average of ',
		chart:' chart ',
		wrong_pic:'Graphical verification code error',
		dismatch:'Two password inputs are inconsistent',
		logon_success:'注册成功',
		attr:'attribute',
		device:'device symbol',
		digital_system:'Digital fishery environment monitoring system(',
		observation_point:' observation point)',
		altitude:'altitude',
		salinity:'salinity',
		setting:'Setting',
		
	},
	'zh-CN': {
		login:'登录',
		logon:'注册',
		
		account_p:'请输入账号',
		pwd_p:'请输入密码',
		pwd_p_a:'再次输入密码确认',
		picture_p:'请输入图形验证码',
		confirm:'确认',
		basic:'基本环境参数',
		temp:'温度',
		ph:'PH值',
		oxygen:'溶解氧浓度',
		history_chart:'历史参数走势表',
		alarm_temp:'温度报警',
		alarm_temp_h:'高温报警设定',
		alarm_temp_l:'低温报警设定',
		alarm_ph:'PH数值报警',
		alarm_ph_h:'PH数值高位报警设定',
		alarm_ph_l:'PH数值低位报警设定',
		alarm_oxygen:'溶解氧浓度报警',
		alarm_oxygen_h:'溶解氧浓度高位报警设定',
		alarm_oxygen_l:'溶解氧浓度低位报警设定',
		max_alarm:'高位预警值设定',
		min_alarm:'低位预警值设定',
		copyright:'版权所属',
		school:'浙大宁波理工学院',
		organization:'智能检测研究所',
		attribute:'属性',
		device:'设备标识符',
		pastday:'距今',
		day:'天',
		average_week:'周平均',
		average_month:'月平均',
		strange_dot:'异常点',
		last_month:'最近三十天',
		last_week:'最近一周',
		last_24h:'24小时',
		last1:'',
		last2:'',
		history:'历史',
		his1:'',
		his2:'',
		his3:'',
		inthelast24:'',
		inthelastweek:'',
		inthelastmonth:'',
		max:'最高数值',
		min:'最低数值',
		average:'平均数值',
		chart:'走势图',
		wrong_pic:'图形验证码错误',
		dismatch:'两次密码输入不一致',
		logon_success:'注册成功',
		attr:'属性',
		device:'设备标识符',
		digital_system:'数字渔场环境监控系统(',
		observation_point:'观测点)',
		altitude:'海拔',
		salinity:'盐度',
		setting:'设置',
	}
}
